services:
 web:
  container_name: fast_api
  build:
   context: ./
   dockerfile: ./Dockerfile
  depends_on:
   - db
  ports:
   - 8080:8080
  restart: on-failure
 db:
  image: postgres:14.1-alpine
  restart: always
  container_name: mb_db
  environment:
   - POSTGRES_DB=postgres
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres_user
  ports:
   - 5432:5432
  volumes:
   - ./db:/var/lib/postgresql/data
   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
